// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsa8M0edzotBOJ1oPw33y0Bqjkimt7DT0',
    appId: '1:344475169694:web:4c77c6b8f973f8cafc1c8f',
    messagingSenderId: '344475169694',
    projectId: 'healthcareapp-8bfd3',
    authDomain: 'healthcareapp-8bfd3.firebaseapp.com',
    storageBucket: 'healthcareapp-8bfd3.firebasestorage.app',
    measurementId: 'G-79226RJ6W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzbXGGhhyPKDPzLqq01Ymk87f8rgHyJYM',
    appId: '1:344475169694:android:b9cb900225f4b517fc1c8f',
    messagingSenderId: '344475169694',
    projectId: 'healthcareapp-8bfd3',
    storageBucket: 'healthcareapp-8bfd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO2dZSdJdrCUELawAu6ltVD18ECtyOq14',
    appId: '1:344475169694:ios:9bca7f447c10a89cfc1c8f',
    messagingSenderId: '344475169694',
    projectId: 'healthcareapp-8bfd3',
    storageBucket: 'healthcareapp-8bfd3.firebasestorage.app',
    iosBundleId: 'com.example.healthCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO2dZSdJdrCUELawAu6ltVD18ECtyOq14',
    appId: '1:344475169694:ios:9bca7f447c10a89cfc1c8f',
    messagingSenderId: '344475169694',
    projectId: 'healthcareapp-8bfd3',
    storageBucket: 'healthcareapp-8bfd3.firebasestorage.app',
    iosBundleId: 'com.example.healthCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsa8M0edzotBOJ1oPw33y0Bqjkimt7DT0',
    appId: '1:344475169694:web:bf8ac5e25697416bfc1c8f',
    messagingSenderId: '344475169694',
    projectId: 'healthcareapp-8bfd3',
    authDomain: 'healthcareapp-8bfd3.firebaseapp.com',
    storageBucket: 'healthcareapp-8bfd3.firebasestorage.app',
    measurementId: 'G-4S099GNM0C',
  );
}
